//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIZCore3DX.NET.RibbonEx.Properties
{


    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여
    // ResGen을 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VIZCore3DX.NET.RibbonEx.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 각도_32px {
            get {
                object obj = ResourceManager.GetObject("각도_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 거리_32px {
            get {
                object obj = ResourceManager.GetObject("거리_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 그림자_32px {
            get {
                object obj = ResourceManager.GetObject("그림자_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 기본단면_32px {
            get {
                object obj = ResourceManager.GetObject("기본단면_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 노트2D_32px {
            get {
                object obj = ResourceManager.GetObject("노트2D_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 노트3D_32px {
            get {
                object obj = ResourceManager.GetObject("노트3D_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 노트모두보이기_32px {
            get {
                object obj = ResourceManager.GetObject("노트모두보이기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 노트모두삭제_32px {
            get {
                object obj = ResourceManager.GetObject("노트모두삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 노트모두숨기기_32px {
            get {
                object obj = ResourceManager.GetObject("노트모두숨기기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 노트선택삭제_32px {
            get {
                object obj = ResourceManager.GetObject("노트선택삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 다른이름저장_32px {
            get {
                object obj = ResourceManager.GetObject("다른이름저장_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 단면상자_32px {
            get {
                object obj = ResourceManager.GetObject("단면상자_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 단면선택삭제_32px {
            get {
                object obj = ResourceManager.GetObject("단면선택삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 단면전체삭제_32px {
            get {
                object obj = ResourceManager.GetObject("단면전체삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 면적_32px {
            get {
                object obj = ResourceManager.GetObject("면적_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모델추가_32px {
            get {
                object obj = ResourceManager.GetObject("모델추가_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모두끄기_32px {
            get {
                object obj = ResourceManager.GetObject("모두끄기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모두선택_32px {
            get {
                object obj = ResourceManager.GetObject("모두선택_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모두초기화_32px {
            get {
                object obj = ResourceManager.GetObject("모두초기화_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모두켜기_32px {
            get {
                object obj = ResourceManager.GetObject("모두켜기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모서리표시_32px {
            get {
                object obj = ResourceManager.GetObject("모서리표시_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 부드러운음영_32px {
            get {
                object obj = ResourceManager.GetObject("부드러운음영_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 비선택끄기_32px {
            get {
                object obj = ResourceManager.GetObject("비선택끄기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 새모델_32px {
            get {
                object obj = ResourceManager.GetObject("새모델_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 색상_32px {
            get {
                object obj = ResourceManager.GetObject("색상_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 선택끄기_32px {
            get {
                object obj = ResourceManager.GetObject("선택끄기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 선택반전_32px {
            get {
                object obj = ResourceManager.GetObject("선택반전_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 선택상자_32px {
            get {
                object obj = ResourceManager.GetObject("선택상자_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 선택상자반복_32px {
            get {
                object obj = ResourceManager.GetObject("선택상자반복_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 선택초기화_32px {
            get {
                object obj = ResourceManager.GetObject("선택초기화_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 선택취소_32px {
            get {
                object obj = ResourceManager.GetObject("선택취소_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 열기_32px {
            get {
                object obj = ResourceManager.GetObject("열기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 와이어다각형_32px {
            get {
                object obj = ResourceManager.GetObject("와이어다각형_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 원근투영_32px {
            get {
                object obj = ResourceManager.GetObject("원근투영_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 은선제거_32px {
            get {
                object obj = ResourceManager.GetObject("은선제거_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 좌표_32px {
            get {
                object obj = ResourceManager.GetObject("좌표_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 초기위치로_32px {
            get {
                object obj = ResourceManager.GetObject("초기위치로_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 최단거리_32px {
            get {
                object obj = ResourceManager.GetObject("최단거리_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 측정모두보이기_32px {
            get {
                object obj = ResourceManager.GetObject("측정모두보이기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 측정모두삭제_32px {
            get {
                object obj = ResourceManager.GetObject("측정모두삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 측정모두숨기기_32px {
            get {
                object obj = ResourceManager.GetObject("측정모두숨기기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 측정선택삭제_32px {
            get {
                object obj = ResourceManager.GetObject("측정선택삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 클립보드로복사_32px {
            get {
                object obj = ResourceManager.GetObject("클립보드로복사_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 투명도_32px {
            get {
                object obj = ResourceManager.GetObject("투명도_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 평행투영_32px {
            get {
                object obj = ResourceManager.GetObject("평행투영_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 표면노트_32px {
            get {
                object obj = ResourceManager.GetObject("표면노트_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 화면에맞춤_32px {
            get {
                object obj = ResourceManager.GetObject("화면에맞춤_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ISOPlus_32px {
            get {
                object obj = ResourceManager.GetObject("ISOPlus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Rotate_XMinus_32px {
            get {
                object obj = ResourceManager.GetObject("Rotate_XMinus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Rotate_XPlus_32px {
            get {
                object obj = ResourceManager.GetObject("Rotate_XPlus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Rotate_YMinus_32px {
            get {
                object obj = ResourceManager.GetObject("Rotate_YMinus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Rotate_YPlus_32px {
            get {
                object obj = ResourceManager.GetObject("Rotate_YPlus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Rotate_ZMinus_32px {
            get {
                object obj = ResourceManager.GetObject("Rotate_ZMinus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Rotate_ZPlus_32px {
            get {
                object obj = ResourceManager.GetObject("Rotate_ZPlus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage X축정렬_32px {
            get {
                object obj = ResourceManager.GetObject("X축정렬_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage XMinus_32px {
            get {
                object obj = ResourceManager.GetObject("XMinus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage XPlus_32px {
            get {
                object obj = ResourceManager.GetObject("XPlus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage XRay_32px {
            get {
                object obj = ResourceManager.GetObject("XRay_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Y축정렬_32px {
            get {
                object obj = ResourceManager.GetObject("Y축정렬_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage YMinus_32px {
            get {
                object obj = ResourceManager.GetObject("YMinus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage YPlus_32px {
            get {
                object obj = ResourceManager.GetObject("YPlus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Z축정렬_32px {
            get {
                object obj = ResourceManager.GetObject("Z축정렬_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ZMinus_32px {
            get {
                object obj = ResourceManager.GetObject("ZMinus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ZPlus_32px {
            get {
                object obj = ResourceManager.GetObject("ZPlus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 간섭검사시작_32px {
            get {
                object obj = ResourceManager.GetObject("간섭검사시작_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 간섭모두삭제_32px {
            get {
                object obj = ResourceManager.GetObject("간섭모두삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 간섭심볼지우기_32px {
            get {
                object obj = ResourceManager.GetObject("간섭심볼지우기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 데칼모두삭제_32px {
            get {
                object obj = ResourceManager.GetObject("데칼모두삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 문자데칼_32px {
            get {
                object obj = ResourceManager.GetObject("문자데칼_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 사용자뷰_32px {
            get {
                object obj = ResourceManager.GetObject("사용자뷰_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 사용자뷰모두삭제_32px {
            get {
                object obj = ResourceManager.GetObject("사용자뷰모두삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 사용자뷰목록_32px {
            get {
                object obj = ResourceManager.GetObject("사용자뷰목록_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 애니메이션시작_32px {
            get {
                object obj = ResourceManager.GetObject("애니메이션시작_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 애니메이션일시정지_32px {
            get {
                object obj = ResourceManager.GetObject("애니메이션일시정지_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 애니메이션정지_32px {
            get {
                object obj = ResourceManager.GetObject("애니메이션정지_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 이미지데칼_32px {
            get {
                object obj = ResourceManager.GetObject("이미지데칼_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 개체로비행_32px {
            get {
                object obj = ResourceManager.GetObject("개체로비행_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 개체로중심이동_32px {
            get {
                object obj = ResourceManager.GetObject("개체로중심이동_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 거리XYZ_32px {
            get {
                object obj = ResourceManager.GetObject("거리XYZ_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 고정구름_32px {
            get {
                object obj = ResourceManager.GetObject("고정구름_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 구름_32px {
            get {
                object obj = ResourceManager.GetObject("구름_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 구조내보내기_32px {
            get {
                object obj = ResourceManager.GetObject("구조내보내기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 글자_32px {
            get {
                object obj = ResourceManager.GetObject("글자_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 단면모두보이기_32px {
            get {
                object obj = ResourceManager.GetObject("단면모두보이기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 단면모두숨기기_32px {
            get {
                object obj = ResourceManager.GetObject("단면모두숨기기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 단면비활성화_32px {
            get {
                object obj = ResourceManager.GetObject("단면비활성화_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 단면활성화_32px {
            get {
                object obj = ResourceManager.GetObject("단면활성화_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 렌더링_32px {
            get {
                object obj = ResourceManager.GetObject("렌더링_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 마크업열기_32px {
            get {
                object obj = ResourceManager.GetObject("마크업열기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 마크업저장_32px {
            get {
                object obj = ResourceManager.GetObject("마크업저장_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모델내보내기_32px {
            get {
                object obj = ResourceManager.GetObject("모델내보내기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 모델트리_32px {
            get {
                object obj = ResourceManager.GetObject("모델트리_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 미니뷰_32px {
            get {
                object obj = ResourceManager.GetObject("미니뷰_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 미리보기_32px {
            get {
                object obj = ResourceManager.GetObject("미리보기_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 박스줌_32px {
            get {
                object obj = ResourceManager.GetObject("박스줌_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 방향전환_32px {
            get {
                object obj = ResourceManager.GetObject("방향전환_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 방향회전Minus_32px {
            get {
                object obj = ResourceManager.GetObject("방향회전Minus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 방향회전Plus_32px {
            get {
                object obj = ResourceManager.GetObject("방향회전Plus_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 분해_32px {
            get {
                object obj = ResourceManager.GetObject("분해_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 뷰툴바_32px {
            get {
                object obj = ResourceManager.GetObject("뷰툴바_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 빠른검색_32px {
            get {
                object obj = ResourceManager.GetObject("빠른검색_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 사각형_32px {
            get {
                object obj = ResourceManager.GetObject("사각형_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 선_32px {
            get {
                object obj = ResourceManager.GetObject("선_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 스케치선택삭제_32px {
            get {
                object obj = ResourceManager.GetObject("스케치선택삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 스케치영역삭제_32px {
            get {
                object obj = ResourceManager.GetObject("스케치영역삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 스케치전체삭제_32px {
            get {
                object obj = ResourceManager.GetObject("스케치전체삭제_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 연속거리_32px {
            get {
                object obj = ResourceManager.GetObject("연속거리_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 연속선_32px {
            get {
                object obj = ResourceManager.GetObject("연속선_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 원_32px {
            get {
                object obj = ResourceManager.GetObject("원_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 음영_32px {
            get {
                object obj = ResourceManager.GetObject("음영_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 자유곡선_32px {
            get {
                object obj = ResourceManager.GetObject("자유곡선_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 조작자_32px {
            get {
                object obj = ResourceManager.GetObject("조작자_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 좌표축_32px {
            get {
                object obj = ResourceManager.GetObject("좌표축_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 축거리측정X_32px {
            get {
                object obj = ResourceManager.GetObject("축거리측정X_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 축거리측정Y_32px {
            get {
                object obj = ResourceManager.GetObject("축거리측정Y_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 축거리측정Z_32px {
            get {
                object obj = ResourceManager.GetObject("축거리측정Z_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 타원_32px {
            get {
                object obj = ResourceManager.GetObject("타원_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 펜_32px {
            get {
                object obj = ResourceManager.GetObject("펜_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 평행면거리_32px {
            get {
                object obj = ResourceManager.GetObject("평행면거리_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 화살표_32px {
            get {
                object obj = ResourceManager.GetObject("화살표_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 환경조명_32px {
            get {
                object obj = ResourceManager.GetObject("환경조명_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage 회전이동_32px {
            get {
                object obj = ResourceManager.GetObject("회전이동_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage BOP_32px {
            get {
                object obj = ResourceManager.GetObject("BOP_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }

        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage COP_32px {
            get {
                object obj = ResourceManager.GetObject("COP_32px", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
    }
}
